#! /bin/bash

user="";
pass="";
db="";
host="localhost";
filepath="./";

# Store tables
filename=$filepath`date "+%y%m%d_%H%M"`_$db.sql;
datatables=`mysql -ND -h$host -u$user -p$pass $db -e "SHOW TABLES" | egrep -v '(^search.*)|(^cache.*)|^(accesslog|cache|sessions|watchdog)$'`;
cachetables=`mysql -ND -h$host -u$user -p$pass $db -e "SHOW TABLES" | egrep '(^search.*)|(^cache.*)|^(accesslog|cache|sessions|watchdog)$'`;

# Create structure and data dumps
echo "Export database...";
mysqldump -h$host -u$user -p$pass --no-data --add-drop-table -e $db $cachetables > $filename;
mysqldump -h$host -u$user -p$pass --add-drop-table -e $db $datatables >> $filename;
# Craete archive
gzip $filename;

echo "The database is exported to $filename.gz";
exit 0;
