#! /bin/bash

user="";
pass="";
db="";
host="localhost";

type drush &>/dev/null && (echo "Clear Drupal cache tables..."; drush cc all;)

echo "Export database...";
mysqldump -h$host -u$user -p$pass $db --add-drop-table -e | gzip > `date "+%y%m%d_%H%M"`_$db.sql.gz;
echo "The database is exported to `date "+%y%m%d_%H%M"`_$db.sql.gz";

exit 0;
